ALTER TABLE "Raid" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "Raid" ADD COLUMN IF NOT EXISTS "deletedByUserId" TEXT;
ALTER TABLE "Raid" ADD COLUMN IF NOT EXISTS "deletedByName" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Raid" ADD COLUMN IF NOT EXISTS "deleteMotif" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Raid" ADD COLUMN IF NOT EXISTS "restoredAt" TIMESTAMP(3);
ALTER TABLE "Raid" ADD COLUMN IF NOT EXISTS "restoredByName" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Raid" ADD COLUMN IF NOT EXISTS "restoreMotif" TEXT NOT NULL DEFAULT '';

CREATE INDEX IF NOT EXISTS "Raid_deletedAt_idx" ON "Raid"("deletedAt");
