-- AlterTable
ALTER TABLE "User" ADD COLUMN "first_name" TEXT NOT NULL DEFAULT '';
ALTER TABLE "User" ADD COLUMN "last_name" TEXT NOT NULL DEFAULT '';
ALTER TABLE "User" ADD COLUMN "phone" TEXT NOT NULL DEFAULT '';
ALTER TABLE "User" ADD COLUMN "email" TEXT NOT NULL DEFAULT '';
